# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a036f38ed3efea0d0d5111e42b7e34e62250455a69b52d6695ff558f7cb103c4bdc5b262a0ff08fd531eae6fe2ec6438f431da30d7c1b41b762bac9758a51c40

test:
  secret_key_base: d2dbec3666ade1bb09cc75829c4df8db5b8fc64b4c07cca3527dd6e116f6fd038ca3307c76559cc33388975810a9cf8d8ee659208fee407b86c3ae60634a1607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
